config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {sessions: 'user/sessions', registrations: 'user/registrations', passwords: 'user/passwords' }
  resources :visits
  resources :vets
  resources :vaccinations
  resources :reminders
  resources :medications
  resources :health_problems
  resources :events
  resources :users
  resources :pets

  root 'welcome#index'

end

app/models/health_problem.rb
class HealthProblem < ActiveRecord::Base
end

app/controllers/health_problems_controller.rb
class HealthProblemsController < ApplicationController
  before_action :set_health_problem, only: [:show, :edit, :update, :destroy]

  # GET /health_problems
  # GET /health_problems.json
  def index
    @health_problems = HealthProblem.find_by_sql ["SELECT * FROM health_problems WHERE \"petID\" = ?", params[:petID].to_i]
  end

  # GET /health_problems/1
  # GET /health_problems/1.json
  def show
  end

  # GET /health_problems/new
  def new
    @health_problem = HealthProblem.new
  end

  # GET /health_problems/1/edit
  def edit
  end

  # POST /health_problems
  # POST /health_problems.json
  def create
    @health_problem = HealthProblem.new(health_problem_params)

    respond_to do |format|
      if @health_problem.save
        format.html { redirect_to @health_problem, notice: 'Health problem was successfully created.' }
        format.json { render :show, status: :created, location: @health_problem }
      else
        format.html { render :new }
        format.json { render json: @health_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /health_problems/1
  # PATCH/PUT /health_problems/1.json
  def update
    respond_to do |format|
      if @health_problem.update(health_problem_params)
        format.html { redirect_to @health_problem, notice: 'Health problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @health_problem }
      else
        format.html { render :edit }
        format.json { render json: @health_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_problems/1
  # DELETE /health_problems/1.json
  def destroy
    @health_problem.destroy
    respond_to do |format|
      format.html { redirect_to health_problems_url, notice: 'Health problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_problem
      @health_problem = HealthProblem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def health_problem_params
      params.require(:health_problem).permit(:dateEntered, :petID, :description, :dateOccurred)
    end
end

app/helpers/health_problems_helper.rb
module HealthProblemsHelper
end

app/views/health_problems/_form.html.erb
<%= form_for(@health_problem) do |f| %>
  <% if @health_problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@health_problem.errors.count, "error") %> prohibited this health_problem from being saved:</h2>

      <ul>
      <% @health_problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dateEntered %><br>
    <%= f.date_select :dateEntered %>
  </div>
  <div class="field">
    <%= f.label :petID %><br>
    <%= f.number_field :petID %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :dateOccurred %><br>
    <%= f.date_select :dateOccurred %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/health_problems/edit.html.erb
<h1>Editing Health Problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @health_problem %> |
<%= link_to 'Back', health_problems_path %>

app/views/health_problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Health Problems</h1>

<table>
  <thead>
    <tr>
      <th>Dateentered</th>
      <th>Petid</th>
      <th>Description</th>
      <th>Dateoccurred</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @health_problems.each do |health_problem| %>
      <tr>
        <td><%= health_problem.dateEntered %></td>
        <td><%= health_problem.petID %></td>
        <td><%= health_problem.description %></td>
        <td><%= health_problem.dateOccurred %></td>
        <td><%= link_to 'Show', health_problem %></td>
        <td><%= link_to 'Edit', edit_health_problem_path(health_problem) %></td>
        <td><%= link_to 'Destroy', health_problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health problem', new_health_problem_path %>

app/views/health_problems/new.html.erb
<h1>New Health Problem</h1>

<%= render 'form' %>

<%= link_to 'Back', health_problems_path %>

app/views/health_problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dateentered:</strong>
  <%= @health_problem.dateEntered %>
</p>

<p>
  <strong>Petid:</strong>
  <%= @health_problem.petID %>
</p>

<p>
  <strong>Description:</strong>
  <%= @health_problem.description %>
</p>

<p>
  <strong>Dateoccurred:</strong>
  <%= @health_problem.dateOccurred %>
</p>

<%= link_to 'Edit', edit_health_problem_path(@health_problem) %> |
<%= link_to 'Back', health_problems_path %>