config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {sessions: 'user/sessions', registrations: 'user/registrations', passwords: 'user/passwords' }
  resources :visits
  resources :vets
  resources :vaccinations
  resources :reminders
  resources :medications
  resources :health_problems
  resources :events
  resources :users
  resources :pets

  root 'welcome#index'

end

app/models/vaccination.rb
class Vaccination < ActiveRecord::Base
end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  before_action :set_vaccination, only: [:show, :edit, :update, :destroy]

  # GET /vaccinations
  # GET /vaccinations.json
  def index
    @vaccinations = Vaccination.find_by_sql ["SELECT * FROM vaccinations WHERE \"petID\" = ?", params[:petID].to_i]
  end

  # GET /vaccinations/1
  # GET /vaccinations/1.json
  def show
  end

  # GET /vaccinations/new
  def new
    @vaccination = Vaccination.new
  end

  # GET /vaccinations/1/edit
  def edit
  end

  # POST /vaccinations
  # POST /vaccinations.json
  def create
    @vaccination = Vaccination.new(vaccination_params)

    respond_to do |format|
      if @vaccination.save
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully created.' }
        format.json { render :show, status: :created, location: @vaccination }
      else
        format.html { render :new }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccinations/1
  # PATCH/PUT /vaccinations/1.json
  def update
    respond_to do |format|
      if @vaccination.update(vaccination_params)
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully updated.' }
        format.json { render :show, status: :ok, location: @vaccination }
      else
        format.html { render :edit }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccinations/1
  # DELETE /vaccinations/1.json
  def destroy
    @vaccination.destroy
    respond_to do |format|
      format.html { redirect_to vaccinations_url, notice: 'Vaccination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaccination
      @vaccination = Vaccination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vaccination_params
      params.require(:vaccination).permit(:dateEntered, :petID, :name, :dateGiven)
    end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/vaccinations/_form.html.erb
<%= form_for(@vaccination) do |f| %>
  <% if @vaccination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vaccination.errors.count, "error") %> prohibited this vaccination from being saved:</h2>

      <ul>
      <% @vaccination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dateEntered %><br>
    <%= f.date_select :dateEntered %>
  </div>
  <div class="field">
    <%= f.label :petID %><br>
    <%= f.number_field :petID %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dateGiven %><br>
    <%= f.date_select :dateGiven %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vaccinations/edit.html.erb
<h1>Editing Vaccination</h1>

<%= render 'form' %>

<%= link_to 'Show', @vaccination %> |
<%= link_to 'Back', vaccinations_path %>

app/views/vaccinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vaccinations</h1>

<table>
  <thead>
    <tr>
      <th>Dateentered</th>
      <th>Petid</th>
      <th>Name</th>
      <th>Dategiven</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vaccinations.each do |vaccination| %>
      <tr>
        <td><%= vaccination.dateEntered %></td>
        <td><%= vaccination.petID %></td>
        <td><%= vaccination.name %></td>
        <td><%= vaccination.dateGiven %></td>
        <td><%= link_to 'Show', vaccination %></td>
        <td><%= link_to 'Edit', edit_vaccination_path(vaccination) %></td>
        <td><%= link_to 'Destroy', vaccination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vaccination', new_vaccination_path %>

app/views/vaccinations/new.html.erb
<h1>New Vaccination</h1>

<%= render 'form' %>

<%= link_to 'Back', vaccinations_path %>

app/views/vaccinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dateentered:</strong>
  <%= @vaccination.dateEntered %>
</p>

<p>
  <strong>Petid:</strong>
  <%= @vaccination.petID %>
</p>

<p>
  <strong>Name:</strong>
  <%= @vaccination.name %>
</p>

<p>
  <strong>Dategiven:</strong>
  <%= @vaccination.dateGiven %>
</p>

<%= link_to 'Edit', edit_vaccination_path(@vaccination) %> |
<%= link_to 'Back', vaccinations_path %>